import React, { useState } from 'react';
import Head from 'next/head';

// Users Data
import users from "../data";

// Icons
import { BsArrowRight, BsArrowLeft, BsGithub } from "react-icons/bs";
import Link from 'next/link';
import Image from 'next/image';

export default function Home() {
  const [currentIndex, setCurrentIndex] = useState(1);
  return (
    <>
      <Head>
        <title>Next.js & Tailwind CSS Slider</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col justify-center items-center md:h-screen h-full w-100 py-4 px-3">
        <div className="max-w-6xl w-full m-auto">

          {users?.map((user, index) => (
            user.id == currentIndex &&
            <div className="userCard grid place-items-center gird-cols-1 md:grid-cols-2 gap-2 md:gap-4 w-full" key={index}>
              <div className="flex justify-center items-center overflow-hidden md:h-max min-h-96 h-max bg-gray-100">
                <img src={user.avatar_url} alt="Card-Image" />
              </div>

              <div className="flex flex-col gap-4 py-4 px-2">
                <h2 className="text-3xl md:text-5xl font-bold">{user.full_name}</h2>
                <p className="text-gray-500 text-sm leading-6">{user.description}</p>

                <div className="flex md:justify-start md:gap-8 items-center mt-2 justify-center gap-10">
                  <button className={`text-xl md:text-2xl ${currentIndex == 1 ? "text-gray-300" : "text-black"}`}
                    onClick={() => {
                      if (currentIndex > 1) setCurrentIndex(currentIndex - 1)
                    }} title="Previous">
                    <BsArrowLeft />
                  </button>

                  <button className={`text-xl md:text-2xl ${currentIndex < users.length ? "text-black" : "text-gray-300"}`}
                    onClick={() => {
                      if (currentIndex < users.length) setCurrentIndex(currentIndex + 1)
                    }} title="Next">
                    <BsArrowRight />
                  </button>
                </div>
              </div>
            </div>
          ))}

        </div>

        <footer className="p-4 flex flex-col justify-center items-center gap-4">
          <ul className="flex justify-center items-center gap-3">
            <li className="text-md" title="Portfolio/Personal Website">
              <Link href="https://ismailium.vercel.app/" legacyBehavior>
                <a target="_blank">
                  <Image src="/ismail-boularbah.jpg" height={26} width={26} className="rounded-full" />
                </a>
              </Link>
            </li>
            <li className="text-2xl" title="GitHub">
              <Link href="https://github.com/boularbahsmail/" legacyBehavior>
                <a target="_blank">
                  <BsGithub />
                </a>
              </Link>
            </li>
          </ul>
          <h5 className="text-xs md:text-sm">
            &copy; 2023 - Made with <span title="Love">❤️</span> by {" "}
            <a href="https://twitter.com/boularbahsmail" target="_blank"
              className="font-bold text-blue-400" title="Twitter">
              Ismailium
            </a>
          </h5>
        </footer>
      </main>
    </>
  )
}
